# Generated by Django 4.0.2 on 2022-02-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('other_name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=64)),
                ('phone', models.PositiveIntegerField()),
                ('birthday', models.PositiveIntegerField()),
                ('is_admin', models.CharField(max_length=64)),
            ],
        ),
    ]
